# Generated by Django 5.2.15 on 2026-07-03 06:25

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulStoneAPP', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField()),
                ('certification_authenticity', ckeditor_uploader.fields.RichTextUploadingField()),
                ('stone_origin', ckeditor_uploader.fields.RichTextUploadingField()),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='products/')),
                ('is_certified', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SoulStoneAPP.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SoulStoneAPP.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
