# Generated by Django 5.2.15 on 2026-07-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoulStoneAPP', '0003_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='benefits',
            new_name='description_and_benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
