# Generated by Django 5.2.15 on 2026-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulStoneAPP', '0008_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('product_purchased', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ 1 Star'), (2, '⭐⭐ 2 Stars'), (3, '⭐⭐⭐ 3 Stars'), (4, '⭐⭐⭐⭐ 4 Stars'), (5, '⭐⭐⭐⭐⭐ 5 Stars')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
