# Generated by Django 5.2.15 on 2026-07-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulStoneAPP', '0011_populate_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='SoulStoneAPP.subcategory'),
            preserve_default=False,
        ),
    ]
