"""
Django settings for SOULSTONE project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*=fsa-7(*5-z3m9*v690p7!zes6^l2u3j&o6mobnyz1f$t%%a&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'SoulStoneAPP',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SOULSTONE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SoulStoneAPP.context_processors.categories',
                'SoulStoneAPP.context_processors.cart',
                'SoulStoneAPP.context_processors.whatsapp',
            ],
        },
    },
]

WSGI_APPLICATION = 'SOULSTONE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SOULSTONE_DB',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

# django-ckeditor
# https://django-ckeditor.readthedocs.io/
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# So @login_required redirects to this project's actual login page instead
# of Django's default /accounts/login/.
LOGIN_URL = 'login'





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'saroonsharu@gmail.com'
EMAIL_HOST_PASSWORD = 'rtpobhetadmayvul'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Order notifications are sent to the first address in ADMINS via mail_admins().
ADMINS = [('SoulStones Admin', EMAIL_HOST_USER)]
EMAIL_SUBJECT_PREFIX = ''  # mail_admins() would otherwise prefix subjects with "[Django] "

# Razorpay
# https://razorpay.com/docs/payments/server-integration/python/
# Keys are added manually (e.g. via environment variables) before payments go live.
RAZORPAY_KEY_ID = 'rzp_test_SLFGCvb0VMW4Dl'
RAZORPAY_KEY_SECRET = '1t5NKclonzMGs1mD9smIywJ3'



RECAPTCHA_SITE_KEY = '6LfL5UktAAAAAIvSZZXxFVpDR3W3VMCNuCbHDTYc'

RECAPTCHA_SECRET_KEY = '6LfL5UktAAAAAEXrskNE_xQ1B-3VF22sECGAYDsi'
# WhatsApp number (with country code, no symbols) used by the "consult-band"
# advisor sections across the site. Change this one value to update every
# WhatsApp button — see SoulStoneAPP.context_processors.whatsapp.
WHATSAPP_NUMBER = '917593029706'

